version: '3'
services:
    web:
        image: alejovillegas7/dockerweb
        build: .
        command: "node index.js"
        ports: 
            - "8081:8080"
        depends_on: 
            - "mongo"
    mongo:
        image: "mongo"
        ports:
            - "27017:27017"